### PR TITLE
Feature/37 add test code coverage

### LINKED ISSUE #37: Add test code coverage
To make sure our tests are adequate, we should have a way to measure how much coverage our tests have (for now, let's require the coverage to be at least 90%, but we can change this value at any time should it be too high or too low).

### PR DESCRIPTION
**Pull request by JR-prog**
Adding test coverage to our CI. What this does is checks how many lines of code are actually being run whenever we test, to help show holes in our testing. For now I set the passing threshold to 90% (some will argue we should strive for 100%, but anyway 100% code coverage doesn't ensure the app is 100% working).

Closes #37 

Also contains some changes from #42 to save some hassle down the line.

### CODE REVIEW

**Comment by JR-prog** [comment]
First build failed (which is a success, because the current backend tests only cover 84%). I will fix these tests and add the frontend tests to this PR.

**Comment by JR-prog** [comment]
As of now the code coverage is working as intended, the checks are only failing because our tests don't cover an adequate amount of our code. Will fix in this PR.

**Comment by JR-prog** [comment]
Note that I had to temporarily lower the backend coverage threshold until we implement the mutation tests (these will be done with the rest of the CRUD operations will be implemented in #5

**Review by KELLOGGS522 — APPROVED** [review]
All the tests pass (with the current threshold) and everything seems to be in order. Merging

**Pull request merged**
